// This file is auto-generated by @hey-api/openapi-ts

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type Recording = {
    file_url: string;
    name: string;
    id: number;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type GetHomeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetHomeGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type InferInferencePostData = {
    body: Recording;
    path?: never;
    query?: never;
    url: '/inference';
};

export type InferInferencePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InferInferencePostError = InferInferencePostErrors[keyof InferInferencePostErrors];

export type InferInferencePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'https://3ca4-131-215-220-52.ngrok-free.app' | (string & {});
};